name: Build

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
    - '**'
  push:
    branches:
    - '**'
    - '!main'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
        - Release
        - Debug
        platform:
        - x64
        - x86
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install Mono
      run: |
        Invoke-WebRequest -Uri 'https://download.mono-project.com/archive/6.12.0/windows-installer/mono-6.12.0.198-x64-0.msi' -OutFile 'mono.msi'
        Start-Process msiexec.exe -Wait -ArgumentList '/i mono.msi /quiet'

    - name: Build
      run: msbuild -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gmml-win-${{ matrix.platform }}-${{ matrix.configuration }}
        path: .\bin\win-${{ matrix.platform }}\${{ matrix.configuration }}
