name: GMML Windows x86

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: msbuild -p:Configuration=Release -p:Platform=x86
    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: gmml-win-x86
        path: .\bin\win-x86\Release

    - name: Build Debug
      run: msbuild -p:Configuration=Debug -p:Platform=x86
    - name: Upload Debug
      uses: actions/upload-artifact@v3
      with:
          name: gmml-win-x86-debug
          path: .\bin\win-x86\Debug
